name: fourmolu
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fourmolu/fourmolu-action@v9
        with:
          pattern: |
            src/**/*.hs
