name: fourmolu
on:
  - push
  - pull_request
  - merge_group
  - workflow_dispatch
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: haskell-actions/run-fourmolu@v12
        with:
          pattern: |
            src/**/*.hs
